name: Build and Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Cache build and test
        id: build-cache
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ matrix.os }}-build-cache

      - name: Test
        run: cargo test

      - name: Build
        run: cargo build --release

      - name: Rename Release assets
        if: matrix.os != 'windows-latest'
        run: |
          mv target/release/jaslog target/release/jaslog_$(uname)
          ls target/release/

      - uses: actions/upload-artifact@v4
        if: matrix.os != 'windows-latest'
        with:
          name: binary-${{ matrix.os }}
          path: target/release/jaslog_*

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: binary-${{ matrix.os }}
          path: target/release/jaslog.exe

  create_release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
      - uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          draft: false
          artifacts: "binary-*/jaslog_*,binary-*/jaslog.exe"
