name: Build and test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Cache build
      id: build-cache
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ matrix.os }}-build-cache

    - name: Run tests
      run: cargo test

    - name: Build
      run: cargo build --release

    - name: Persist binary Linux
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v1
      with:
        name: jaslog_linux
        path: target/release/jaslog

    - name: Persist binary macOS
      if: matrix.os == 'macOS-latest'
      uses: actions/upload-artifact@v1
      with:
        name: jaslog_macos
        path: target/release/jaslog

    - name: Persist binary Windows
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v1
      with:
        name: jaslog_windows.exe
        path: target/release/jaslog.exe

  release:
    if: github.ref == 'v*'
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
